---
title: 'test'
output:
  html_document:
    pandoc_args: "--dpi=200"
    fig_height: 3
    fig_width: 5
    code_folding: show
    df_print: kable
    toc: true
    toc_depth: 3
    toc_float: true
editor_options: 
  chunk_output_type: console
---


Hi! Here are some words.


# One semi standard heading as a sort of header at the top of the document

```{r, echo=FALSE}


df1 = data.frame(
  df = 111,
  "Date Submitted" = "1/1/1999",
  "Date Required" = "1/1/2020",
  Description = "words",
  "Link to File/Folder" = "hre/here/there",
  "Approx Time Needed?" = NA, 
  Requestor = "Me"
)



DT::datatable(df1, 
							extensions = "Buttons",
							rownames = F, 
							options = list(dom = 'B',
														 scrollX = TRUE,
														 buttons = list(list(extend = 'copy', 
														 										title = NULL, 
														 										header = FALSE))) )




```

\
\
\
\



# Setup
```{r setup}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, results = "asis")
suppressMessages(library(tidyverse))
suppressMessages(library(tidylog))
suppressMessages(library(data.table))
suppressMessages(library(DT))



```





\
\
\
\






# Some results later on

```{r, echo=FALSE}


df2 = data.frame(
  v1 = 111,
  v2 = "1/1/1999",
  "Var 3" = "1/1/2020"
)



DT::datatable(df2, 
							extensions = "Buttons",
							rownames = F, 
							options = list(dom = 'B',
														 scrollX = TRUE,
														 buttons = list(list(extend = 'copy', 
														 										title = NULL, 
														 										header = FALSE))) )




```

\
\
\
\



```{r session info}

pander::pander(sessionInfo())

```
